export const data = {
    Categories: ["electronics", "Sports", "Furnture", "clothing", "Shoes", "jewelery"],
    Products: [
        {id:1, name: "", Category: "clothing",
    description: "", price: 20},
        {id:2, name: "TV",Category: "clothing",
        description: "", price: 20},
        {id:3, name: "Tablet", Category: "clothing",
        description: "", price: 20},
        {id:4, name: "Camera", Category: "clothing",
        description: "", price: 20},
        {id:5, name: "Fjallraven", Category: "clothing",
        description: "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
        price: 20, image:"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"},
        {id:6, name: "Mens Casual Premium Slim Fit T-Shirts", Category: "clothing",
        description: "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
        price: 22.3, image:"https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg"},
        {id:7, name: "Mens Cotton Jacket", Category: "clothing",
        description: "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
         price: 55.99, image:"https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg"},
        {id:8, name:"Mens Casual Slim Fit", Category: "clothing",
        description: "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
        price: 15.99, image:"https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg"},
        {id:9, name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet", Category: "jewelery",
        description: "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
        price: 695, image:"https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg"},
        {id:10, name: "Solid Gold Petite Micropave", Category: "jewelery",
        description: "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
        price: 168, image:"https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg"},
        {id:11, name: "White Gold Plated Princess", Category: "jewelery",
        description: "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
        price: 9.99, image:"https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg"},
        {id:12, name: "Pierced Owl Rose Gold Plated Stainless Steel Double", Category: "jewelery",
        description: "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
        price: 10.99, image:"https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg"},
        {id:13, name: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ", Category: "electronics",
        description: "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
        price: 64, image:"https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg"},
        {id:14, name: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s", Category: "electronics",
        description: "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
        price: 109, image:"https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg"},
        {id:15, name: "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5", Category: "clothing",
        description: "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
        price: 109, image:"https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg"},
        {id:4, name: "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive", Category: "electronics",
        description: "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
        price: 114, image:"https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg"},
        {id:4, name: "Running sneaker", Category: "shoes",
        description: "running-sneaker", price: 200, image: null},
        {id:4, name: "men casual shoes sports running sneakers", Category: "shoes",
        description: "men-casual-shoes-sports-running-sneakers", price: 100, image: null},
        {id:4, name: "premium leather matt black casual boot", Category: "shoes",
        description: "premium-leather-matt-black-casual-boot", price: 250, image: null},
        {id:4, name: "waterproof fitness racker sports watch", Category: "sports",
        description: "waterproof-fitness-racker-sports-watch", price: 140, image: null},
        {id:4, name: "bracelet blood pressure sport fitness smartwatch", Category: "sports",
        description: "bracelet-blood-pressure-sport-fitness-smartwatch", price: 120, image: null},
        {id:4, name: "ASUS Full HD HDMI Sync Eye Care eSports Gaming Monitor", Category: "electronics",
        description: "asus-full-hd-hdmi-sync-eye-care-esports-gaming-monitor", price: 159, image: null},
        {id:4, name: "iphone 13 pro black color 512gb storage", Category: "electronics",
        description: "iphone-13-pro-black-color-512gb-storage", price: 999, image: null},
        {id:4, name: "RGB Gaming Chair with Lights and Speakers", Category: "furniture",
        description: "rgb-gaming-chair-with-lights-and-speakers", price: 600, image: null},
        {id:4, name: "Bed Storage Leather Italian Furniture Sofa Luxury", Category: "furniture",
        description: "bed-storage-leather-italian-furniture-sofa-luxury", price: 750, image: null},
        {id:4, name: "heart rate monitor gps fitness smartwatch", Category: "sports",
        description: "heart-rate-monitor-gps-fitness-smartwatch", price: 200, image: null},
        {id:4, name: "men Shoes", Category: "shoes",
        description: "men-Shoes", price: 45, image: null},
        {id:4, name: "women's fashion", Category: "clothing",
        description: "womens-fashion", price: 45, image: null}
    ]
}